server:
  port: 8090

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  redis:
    #数据库索引
    database: 8
    host: localhost
    port: 6379
    password:
    #连接超时时间
    timeout: 5000ms
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: douyin
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
  # 同意实体类对应多张表
  main:
    allow-bean-definition-overriding: true
  # shardingJDBC分片策略
  shardingsphere:
    datasource:
      names: douyin0,douyin1
      douyin0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/douyin?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        username: root
        password: 123456
      douyin1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/douyin?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        username: root
        password: 123456
    # 开启sql日志输出
    #    props:
    #      sql:
    #        show: true
    sharding:
      master-slave-rules:
        # 逻辑库ds0
        ds0:
          # 主数据库
          master-data-source-name: douyin0
          # 从数据库
          slave-data-source-names: douyin1

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名规则的转换
    call-setters-on-nulls: true # 如果查询结果中包含空值的列，则 mybatis 在映射的时候，不会映射这个字段
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl